### ISSUE TITLE
Serverless on IBM i (part 1)

### ISSUE THREAD

**Issue by worksofliam** [worksofliam/blog#38]
## Serverless on IBM i

Serverless is a technology that is being used heavily in the AWS and Google Cloud Platform world. This blog post is going to talk about Serverless, FAAS and if it’s possible on IBM i.

### What is Serverless

Right now, businesses are migrating their software stack from in-house to some kind of cloud provider. This means instead of the business managing the hardware and the software stack (their LPARs or VMs), they no longer need to manage the hardware. It usually also means they don’t pay for what they use - it may cost them more money at high traffic times than otherwise.

Serverless goes one step behind that and removes the need to manage the LPARs and VMs and only focus on writing the code for their business. That’s right -  AWS, GCP, and other cloud providers are offering a service where the developers and business only have to worry about the code. No more worrying about what hardware it’s running on OR worrying about what servers it’s running on since that is all managed for you.

The idea behind Serverless is that the business can just focus on developing their code and Serverless can maintain where it is hosted and deployed for you. For example, with Serverless I can spin up a new database and multiple separate functions within my instance to work with each other - without worrying about any virtual machines, in the cloud. A developer can write a specific function (which might be callable via a web service, or other methods) and deploy that single function within minutes.

Let’s say I have a Serverless instance with a table named `inventory`. Then, I may have multiple different functions to interact with that table: list and filter inventory function, add new item, remote item, change item quantity, etc. All that matters is that these are all separate functions, but are also managed by the cloud provider.

Most ‘functions’ when invoked are run in containers too, which might be spun up when the function is called and then shut down again when it’s finished with - great for security.

### Where does IBM i come in?

Serverless or Function As A Service (FAAS) doesn’t really exist right now. Serverless cannot really exist for IBM i at the moment because the infrastructure for Serverless doesn’t exist. To me it seems like the popular languages/runtimes being used in Serverless environments are Node.js, Python and Go.

* IBM i in any cloud costs a lot of money
* The software to maintain FAAS doesn’t exist for IBM i
* There is ‘agnostic FAAS hosting’ software, but isn’t really supported on IBM i because a lot of them require Docker (for containerising).
* For true Serverless environment, a hosting company would have to have the infrastructure to host Serverless applications - which of course costs money upfront.

While Serverless won’t be available yet, private FAAS is absolutely doable when the software stack exists. There are two parts to this software stack:

* The part which runs on the host server, to maintain your functions and keep them running
* The CLI tools to test and deploy onto a host server from the development machine (or a CI environment)

As I mentioned before, the agnostic managers can’t really work on IBM i because of the lack of Docker support - which sadly probably means reinventing something specifically for IBM i (or a more generic one). For example, let’s say I had this Node.js web service function that I want to deploy:

```javascript
//index.js
module.exports.hellofunc = async (req, res) => {
  res.send(‘Hello world’);
}
```

There would also be some kind of configuration file for this function for when it is deployed:

```json
{
    "group": "example",
    "functions": [
        {"path": "/helloworld", "method": "get", "handler": "hellofunc"}
    ]
}
```

From here, it should be very very simple to deploy this to my host machine:

```
$ cd /hwexample
$ serverlessi —connect myibmi
$ serverlessi —deploy
Function deployed at http://myibmi/example/helloworld
```

... or something like that. Again, this toolset doesn't exist yet but it would be neat. Maybe one day :)

**Comment by kadler** [comment]
> It usually also means they don’t pay for what they use

"don't pay for what they _don't_ use" or "only pay for what they use"

**Comment by kadler** [comment]
> Serverless cannot really exist for IBM i at the moment because the infrastructure for Serverless doesn’t exist.

This seems like a false premise. Why is IaaS required for FaaS?
