### ISSUE TITLE
Vs Code on V7R1 - error code  38501

### ISSUE THREAD

**Issue by HBNGitAdmin** [worksofliam/blog#71]
Hello,

While connecting to the IBM i server it gets error code (38501) - see attachment -   because the CCSID is not set (65535) and it does not provide the "User Library list" or any source member in the "Object Browser". The IBM i is on V7R1.  

Thanks,
John

![image](https://github.com/user-attachments/assets/6ee75868-d693-4c17-a4f9-a506366a2e72)

**Comment by worksofliam** [comment]
Wrong repo.
