### ISSUE TITLE
Best Approach for Managing Source Code on IBM i with Git and Distributed Teams in VS Code

### ISSUE THREAD

**Issue by ghitti** [worksofliam/blog#72]
Hi Liam,

I'm trying to solve a challenge related to source code management on IBM i using Git in a distributed team environment. Currently, I have two teams that need to collaborate, but there's a specific issue when using Git with VS Code while working with code on the IFS on IBM i:

**Team A** has direct access to IBM i, and we work with the source code stored in the IFS using VS Code. However, when the sources are in the IFS, the Git features are not integrated in VS Code, which limits the efficiency of our workflow compared to working with local repositories.
**Team B** does not have direct access to IBM i and can only work through GitLab or with local repositories on their PCs.

**Dilemma:**
I'm considering two possible scenarios:

Git repository in the IFS on IBM i: Initialize and manage a Git repository in the IFS and synchronize it with GitLab. However, as mentioned, this reduces the Git functionality within VS Code (e.g., we cannot use the integrated Source Control).

Local repositories on PCs for both teams: Allow both teams (including Team A) to work with local Git repositories on their PCs and synchronize changes with GitLab, which in turn syncs with IBM i. This would allow everyone to use the full Git features in VS Code but introduces an extra layer of synchronization.

In this situation, what do you think would be the best approach to balance the ease of using Git's features in VS Code and accessing the code on IBM i?

Thanks a lot for your time and valuable advice!

**Comment by worksofliam** [comment]
Hi. This repo isn't for questions. Sorry!

**Comment by richardschoen** [comment]
Put those source files back on IBMi and take a look at iForgit.  https://www.iforgit.com
